Repository OZ-Coding-School/oz_02_collabo-007, pull requests merged in 2024-05, with the labels that each got.

#20 design: 로그인 페이지 마크업
  app/_asset/icons/check.svg
  app/_asset/icons/visible.svg
  app/login/page.tsx
  app/page.tsx
  components/organism/LoginForm/InputPassword.tsx
  components/template/expamle/example.tsx
  styles/globals.css
  tailwind.config.ts
Labels: FE_전소희, Design

#22 feat: 회원가입 페이지
  app/_asset/icons/add.svg
  app/_asset/icons/chevron-left.svg
  app/_asset/icons/search.svg
  app/_asset/icons/visible-off.svg
  app/_asset/icons/x.svg
  app/layout.tsx
  app/signup/page.tsx
  components/core/Button/Button.tsx
  components/core/HelperText/HelperText.tsx
  components/core/Input/Input.tsx
  components/core/Label/Label.tsx
  components/core/NavItem/NavItem.tsx
  components/module/InputModule/InputModule.tsx
  components/organism/signupForm/BirthField/BirthField.tsx
  components/organism/signupForm/ClubField/ClubField.tsx
  components/organism/signupForm/ClubField/ClubModal/ClubContent.tsx
  components/organism/signupForm/ClubField/ClubModal/ClubItem.tsx
  components/organism/signupForm/ClubField/ClubModal/ClubModal.tsx
  components/organism/signupForm/GenderField/GenderField.tsx
  components/organism/signupForm/HeaderBar/HeaderBar.tsx
  components/organism/signupForm/NameField/NameField.tsx
  components/organism/signupForm/PasswordField/PasswordField.tsx
  components/organism/signupForm/PhoneField/PhoneField.tsx
  components/organism/signupForm/ProfileField/ProfileField.tsx
  components/organism/signupForm/index.tsx
  lib/hook/useClickOutsideModal.ts
  package-lock.json
  package.json
  public/tennis.jpeg
  styles/globals.css
Labels: FE_강혁준, Feat

#25 feat: 마이 페이지 마크업
  .prettierrc
  app/_asset/icons/check-circle.svg
  app/layout.tsx
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  app/mypage/record/page.tsx
  app/signup/page.tsx
  components/core/Button/Button.tsx
  components/core/ClubIcon/ClubIcon.tsx
  components/core/TeamIcon/TeamIcon.tsx
  components/module/HeaderBar/HeaderBar.tsx
  components/module/MatchResultCard/MatchResultCard.tsx
  components/module/Navbar/Navbar.tsx
  components/module/ScoreBoard/ScoreBoard.tsx
  components/organism/MyPageSection/MyProfileSection/ClubTab/ClubTab.tsx
  components/organism/MyPageSection/MyProfileSection/MyProfileSection.tsx
  components/organism/MyPageSection/MyProfileSection/ProfileTab/ProfileTab.tsx
  components/organism/MyPageSection/NavigationTab/NavigationTab.tsx
  components/organism/MyPageSection/SignoutTab/SignoutTab.tsx
  components/organism/MyPageSection/index.tsx
  components/organism/MyRecordPageSection/CompRecordBoard/CompRecordBoard.tsx
  components/organism/MyRecordPageSection/CompRecordBoard/RecordBoardHeader/RecordBoardHeader.tsx
  components/organism/MyRecordPageSection/TotalRecord/TotalRecord.tsx
  components/organism/MyRecordPageSection/index.tsx
  components/organism/SignupForm/BirthField/BirthField.tsx
  components/organism/SignupForm/ClubField/ClubField.tsx
  components/organism/SignupForm/ClubField/ClubModal/ClubContent.tsx
  components/organism/SignupForm/ClubField/ClubModal/ClubItem.tsx
  components/organism/SignupForm/ClubField/ClubModal/ClubModal.tsx
  components/organism/SignupForm/GenderField/GenderField.tsx
  components/organism/SignupForm/NameField/NameField.tsx
  components/organism/SignupForm/PasswordField/PasswordField.tsx
  components/organism/SignupForm/PhoneField/PhoneField.tsx
  components/organism/SignupForm/ProfileField/ProfileField.tsx
  components/organism/SignupForm/index.tsx
  components/organism/signupForm/GenderField/GenderField.tsx
  components/organism/signupForm/NameField/NameField.tsx
  tailwind.config.ts
Labels: FE_강혁준, Feat

#30 refactor 로그인 페이지,홈 페이지 레이아웃 수정
  .npmrc
  .nvmrc
  .vscode/setting.json
  app/_asset/icons/chevron-right-primary.svg
  app/data.js
  app/mypage/comp/page.tsx
  app/mypage/edit/page.tsx
  app/mypage/record/page.tsx
  app/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/core/CardPannelContent.tsx/CompetitionStatusPannel.tsx
  components/core/CardPannelContent.tsx/NextMatchInfoPannel.tsx
  components/core/HeaderBar/HeaderBar.tsx
  components/module/CardPannel/CardPannel.tsx
  components/module/HomeUserProfile/HomeUserProfile.tsx
  components/module/Navbar/UserProfileCompNavbar.tsx
  components/organism/CompCard/CompCard.tsx
  components/organism/CompList/CompList.tsx
  components/organism/SigninForm/InputPassword.tsx
  components/organism/SignupForm/ClubField/ClubModal/ClubContent.tsx
  styles/globals.css
Labels: Refactor, FE_전소희

#33 feat: 마이페이지 최근 참가 대회 마크업
  app/mypage/comp/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signin/page.tsx
  components/organism/CompList/CompList.tsx
Labels: FE_전소희, Feat

#35 feat: 프로필 페이지 마크업
  app/(profile)/club/[id]/member/page.tsx
  app/(profile)/club/[id]/page.tsx
  app/(profile)/team/[id]/member/page.tsx
  app/(profile)/team/[id]/page.tsx
  app/(profile)/user/[id]/record/page.tsx
  app/layout.tsx
  app/mypage/page.tsx
  components/core/Avatar/Avatar.tsx
  components/core/UserProfile/UserProfile.tsx
  components/module/UserProfileCard/UserProfileCard.tsx
  components/organism/MyPageSection/MyProfileSection/ClubTab/ClubTab.tsx
  components/organism/ProfilePage/ClubBanner/ClubBanner.tsx
  components/organism/ProfilePage/InfoBanner/InfoBanner.tsx
  components/organism/ProfilePage/MemberCard/MemberCard.tsx
  components/organism/ProfilePage/TeamBanner/TeamBanner.tsx
  components/organism/ProfilePage/index.ts
Labels: FE_강혁준, Feat

#37 feat: 대회페이지 대회리스트 마크업
  app/_asset/icons/dropdown.svg
  app/competition/page.tsx
  components/core/CompetitionStatusPanel/CompetitionStatusPanel.tsx
  styles/globals.css
Labels: FE_전소희, Feat

#40 feat: 로그인 기능 구현
  app/signin/actions.tsx
  app/signin/page.tsx
  components/organism/SigninForm/InputPassword.tsx
  components/organism/SigninForm/InputPhone.tsx
  components/organism/SigninForm/SigninForm.tsx
  components/organism/SigninForm/SigninFormContent.tsx
  lib/utils/signInValidation.ts
Labels: Refactor, FE_강혁준, FE_전소희, Feat

#47 feat: 클럽 검색 기능
  @types/club.d.ts
  @types/modal.d.ts
  @types/signup.d.ts
  app/signup/actions.tsx
  app/signup/page.tsx
  components/module/Modal/Modal.tsx
  components/module/Modal/ModalContainer.tsx
  components/organism/SignupForm/ClubField/ClubField.tsx
  components/organism/SignupForm/ClubField/ClubItem.tsx
  components/organism/SignupForm/SignUpForm.tsx
  components/organism/SignupForm/SignUpFormContent.tsx
  lib/hook/hangulToJamo.ts
  lib/hook/useDebounce.ts
Labels: FE_강혁준, Feat

#54 feat: 홈페이지,마이페이지 유저 프로필
  app/(profile)/user/[id]/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  components/core/CategoryRankingCard/CategoryRankingCard.tsx
  components/module/HomeUserProfile/HomeUserProfile.tsx
  components/organism/MyPageSection/MyProfileSection/ClubTab/ClubTab.tsx
  components/organism/MyPageSection/MyProfileSection/MyProfileSection.tsx
  components/organism/MyPageSection/MyProfileSection/ProfileTab/ProfileTab.tsx
  next.config.mjs
Labels: Refactor, FE_전소희, Feat

#61 refactor: 로그인 페이지
  app/signin/actions.tsx
  components/organism/SigninForm/InputPassword.tsx
  components/organism/SigninForm/InputPhone.tsx
  components/organism/SigninForm/SigninForm.tsx
  components/organism/SigninForm/SigninFormContent.tsx
Labels: Refactor, FE_전소희

#65 rename: 컴포넌트 이름 변경
  app/(profile)/user/[id]/page.tsx
  app/competition/page.tsx
  app/mypage/comp/page.tsx
  app/page.tsx
  app/signin/page.tsx
  components/module/CardPanel/CardPanel.tsx
  components/module/CompList/CompCard/CompCard.tsx
  components/module/CompList/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompList/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompList/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompList/CompList.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/ProfilePage/UserPage/UserProfileRankingCard/UserProfileRankingCard.tsx
  components/organism/SignInPage/InputPassword.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignInPage/SigninForm.tsx
  components/organism/SignInPage/SigninFormContent.tsx
  styles/globals.css
  tailwind.config.ts
Labels: Refactor, FE_전소희

#68 refactor: 타입 수정 및 회원가입 alert창
  @types/club.d.ts
  @types/image.d.ts
  @types/modal.d.ts
  @types/signup.d.ts
  @types/team.d.ts
  @types/user.d.ts
  app/(profile)/club/[id]/page.tsx
  app/(profile)/team/[id]/page.tsx
  app/(profile)/user/[id]/page.tsx
  app/mypage/edit/editUser.ts
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signup/page.tsx
  components/core/Dialog/Dialog.tsx
  components/module/MemberProfile/MemberProfile.tsx
  components/module/MemberSection/MemberSection.tsx
  components/module/ModalContainer/ModalContainer.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/MyPage/MyProfileCard/ClubTab/ClubTab.tsx
  components/organism/MyPage/MyProfileCard/MyProfileCard.tsx
  components/organism/MyPage/SignOutButton/SignOutButton.tsx
  components/organism/ProfilePage/UserPage/UserProfileRankingCard/UserProfileRankingCard.tsx
  components/organism/SignUpPage/ChangePasswordForm/ChangePasswordField/ChangePasswordField.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/ClubField/ClubItem.tsx
  components/organism/SignUpPage/SignUpForm.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  middleware.ts
Labels: Refactor, FE_강혁준, FE_전소희

#67 refactor: 홈페이지 compCard 레이아웃 수정
  components/module/CompList/CompCard/CompCard.tsx
Labels: Refactor, FE_전소희

#74 feat: 미들웨어 alert창
  app/page.tsx
  components/core/Alert/Alert.tsx
  components/core/Dialog/Dialog.tsx
  middleware.ts
Labels: FE_강혁준, Feat

#70 refactor: 로그인 페이지
  app/signin/actions.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignInPage/SigninForm.tsx
  components/organism/SignInPage/SigninFormContent.tsx
Labels: Refactor, FE_전소희

#72 refactor: CompList 사용 페이지 레이아웃 수정
  app/(profile)/user/[id]/page.tsx
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  app/page.tsx
Labels: Refactor, FE_전소희

#77 feat: 비밀번호 변경 기능 구현 & fix: build 시 에러 수정
  .eslintrc.json
  @types/signup.d.ts
  @types/user.d.ts
  app/(profile)/club/[id]/member/page.tsx
  app/(profile)/team/[id]/member/page.tsx
  app/(profile)/user/[id]/page.tsx
  app/getMyData.ts
  app/mypage/competition/page.tsx
  app/mypage/edit/changePassword.ts
  app/mypage/edit/editUser.ts
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/signin/signInUser.tsx
  app/signup/getClubList.ts
  app/signup/page.tsx
  app/signup/signUpUser.ts
  components/organism/SignInPage/SigninForm.tsx
  components/organism/SignUpPage/ChangePasswordForm/ChangePasswordForm.tsx
  components/organism/SignUpPage/SignUpForm.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  lib/hook/hangulToJamo.ts
  lib/utils/svg.d.ts
Labels: FE_강혁준, Feat

#78 feat: 로딩 구현
  @types/competition.d.ts
  app/competition/page.tsx
  app/data.js
  app/mypage/competition/page.tsx
  components/core/Skeleton/CompCardSkeleton.tsx
  components/core/Skeleton/CompListSkeleton.tsx
  components/module/CompList/CompList.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompListSection/CompList/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/SignInPage/InputPhone.tsx
  styles/globals.css
Labels: Refactor, FE_전소희, Feat

#81 feat: storybook 추가 및 formdata 수정
  .storybook/main.ts
  app/mypage/edit/changePassword.ts
  app/signin/signInUser.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
  lib/utils/signInValidation.ts
  lib/utils/validation.ts
  next.config.mjs
  stories/Avatar.stories.tsx
  stories/MatchResultCard.stories.tsx
  stories/MemberSection.stories.tsx
  stories/ResultCard.stories.tsx
Labels: FE_강혁준, Feat

#82 fix: 빌드 에러 수정
  @types/competition.d.ts
  app/competition/page.tsx
  app/page.tsx
  components/core/Skeleton/CompListSkeleton.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompListSection/CompList/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/module/UserProfile/UserProfile.tsx
Labels: Fix, FE_전소희

#87 refactor: 로그인 페이지 리팩토링
  @types/signin.d.ts
  @types/signup.d.ts
  app/mypage/edit/editUser.ts
  app/signin/page.tsx
  app/signin/signInUser.tsx
  app/signup/signUpUser.ts
  components/module/Navbar/Navbar.tsx
  components/organism/SignInPage/InputPassword.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignInPage/SignInForm.tsx
  components/organism/SignInPage/SignInFormContent.tsx
  components/organism/SignInPage/SigninForm.tsx
  components/organism/SignInPage/SigninFormContent.tsx
  components/organism/SignUpPage/BirthField/BirthField.tsx
  components/organism/SignUpPage/ConfirmPasswordField/ConfirmPasswordField.tsx
  components/organism/SignUpPage/NameField/NameField.tsx
  components/organism/SignUpPage/PasswordField/PasswordField.tsx
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
  components/organism/SignUpPage/SignUpDialog/SignUpDialog.tsx
  components/organism/SignUpPage/SignUpForm.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  components/organism/SignUpPage/index.ts
  lib/hook/useSignInForm.ts
  lib/hook/useSignUpForm.ts
  lib/utils/changePhoneNumber.ts
  lib/utils/signInValidation.ts
  lib/utils/validation.ts
Labels: Refactor, FE_강혁준

#89 feat: 휴대폰 중복 검사 기능 추가
  @types/signup.d.ts
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
  components/organism/SignUpPage/SignUpForm.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
Labels: FE_강혁준, Feat

#93 Feature/hyunkyung1231/#91
  @types/competition.d.ts
  app/_asset/icons/textcopy.svg
  app/competition/[id]/page.tsx
  components/core/CopyButton/CopyButton.tsx
  components/module/CompInfoCard/CompInfoCard.tsx
  components/organism/CompetitionPage/DetailPage/CompButton/CompButton.tsx
  components/organism/CompetitionPage/DetailPage/CompDetail/CompDetail.tsx
  components/organism/CompetitionPage/DetailPage/ImageBanner/ImageBanner.tsx
Labels: Feat, FE_이현경

#94 feat: 대회 페이지 구현
  @types/competition.d.ts
  app/competition/getCompData.ts
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/organism/CompetitionPage/CompListFilter/CompListFilter.tsx
Labels: FE_전소희, Feat

#96 refactor: 공통 컴포넌트 리팩토링
  components/core/Button/Button.tsx
  components/core/HelperText/HelperText.tsx
  components/core/Input/Input.tsx
  components/module/InputModule/InputModule.tsx
  components/module/ModalContainer/ModalContainer.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/SignInPage/InputPassword.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignUpPage/BirthField/BirthField.tsx
  components/organism/SignUpPage/ChangePasswordForm/ChangePasswordField/ChangePasswordField.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/ConfirmPasswordField/ConfirmPasswordField.tsx
  components/organism/SignUpPage/NameField/NameField.tsx
  components/organism/SignUpPage/PasswordField/PasswordField.tsx
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
Labels: Refactor, FE_강혁준

#99 refactor : handleCopyClick 코드 호환성문제로 수정
  components/core/CopyButton/CopyButton.tsx
  components/core/CopyModal/CopyModal.tsx
  components/module/CompInfoCard/CompInfoCard.tsx
Labels: Refactor, Feat, FE_이현경

#101 refactor: competition 페이지 리팩토링
  app/competition/page.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompList.tsx
  lib/utils/formatDate.ts
Labels: Refactor, FE_전소희

#105 refactor: 모달 컴포넌트 리팩토링
  @types/modal.d.ts
  components/module/Modal/Modal.tsx
  components/module/ModalContent/ModalContent.tsx
  components/organism/SignInPage/InputPassword.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignUpPage/BirthField/BirthField.tsx
  components/organism/SignUpPage/ChangePasswordForm/ChangePasswordForm.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/ConfirmPasswordField/ConfirmPasswordField.tsx
  components/organism/SignUpPage/NameField/NameField.tsx
  components/organism/SignUpPage/PasswordField/PasswordField.tsx
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
  components/organism/SignUpPage/SignUpDialog/SignUpDialog.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  lib/hook/useModalContent.ts
Labels: Refactor, FE_강혁준

#107 refactor: signin 페이지 리팩토링
  app/competition/page.tsx
  app/page.tsx
  app/signin/signInUser.tsx
  components/core/Avatar/ProfileAvatar.tsx
  components/core/Skeleton/CompCardSkeleton.tsx
  components/organism/SignInPage/InputPassword.tsx
  components/organism/SignInPage/InputPhone.tsx
  components/organism/SignInPage/SignInForm.tsx
  components/organism/SignInPage/SignInFormContent.tsx
  lib/hook/useSignInForm.ts
  lib/utils/validation.ts
Labels: Refactor, FE_전소희

#108 feat : 대회 상세 조회 페이지 로딩UI 기능 추가
  app/_asset/icons/tennis-ball.svg
  app/competition/[id]/getCompDetail.ts
  app/competition/[id]/page.tsx
  app/competition/getCompData.ts
  components/core/CopyButton/CopyButton.tsx
  components/core/Skeleton/CompDetailSkeleton.tsx
  components/module/CompDetailSection/CompDetailSection.tsx
  components/organism/CompetitionPage/DetailPage/CompButton/CompButton.tsx
  components/organism/CompetitionPage/DetailPage/CompDetail/CompDetail.tsx
Labels: Refactor, Feat, FE_이현경

#111 feat: 대회 신청 페이지
  app/competition/[id]/apply/applyCompetition.ts
  app/competition/[id]/apply/page.tsx
  app/competition/[id]/getCompDetail.ts
  app/competition/[id]/success/page.tsx
  components/module/CompDetailSection/CompDetailSection.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/ApplyForm.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/ApplyFormContent.tsx
  components/organism/CompetitionPage/DetailPage/CompButton/CompButton.tsx
  components/organism/SignUpPage/SignUpDialog/SignUpDialog.tsx
  lib/hook/useApplyForm.ts
Labels: FE_강혁준, Feat
