Repository OZ-Coding-School/oz_02_collabo-007, pull requests merged in 2024-04, with the labels that each got.

#3 conf: 초기 개발 환경 세팅
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  app/api/dummy.txt
  app/favicon.ico
  app/layout.tsx
  app/page.tsx
  components/core/Button/Button.tsx
  components/core/Button/button.css
  components/module/dummy.txt
  components/template/dummy.txt
  lib/dummy.txt
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  stories/Button.stories.ts
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: FE_강혁준, FE_전소희, Conf

#11 Navbar(공통 컴포넌트) 생성
  .eslintrc.json
  .prettierrc.json
  components/core/NavItem/NavItem.tsx
  components/module/Navbar/Navbar.tsx
  package-lock.json
  package.json
  public/icons/award-filled.svg
  public/icons/award.svg
  public/icons/flag-filled.svg
  public/icons/flag.svg
  public/icons/home-filled.svg
  public/icons/home.svg
  public/icons/user-filled.svg
  public/icons/user.svg
  stories/Navbar.stories.tsx
Labels: FE_강혁준, Feat

#10 Input(공동컴포넌트) 생성
  components/core/HelperText/HelperText.tsx
  components/core/Input/Input.tsx
  lib/utils/svg.d.ts
  public/error-circle.svg
  public/success-circle.svg
  public/warning-circle.svg
  stories/Input.stories.tsx
Labels: FE_전소희, Feat

#17 refactor: navbar css 수정
  components/core/NavItem/NavItem.tsx
  components/module/Navbar/Navbar.tsx
Labels: Refactor, FE_강혁준

#14 fix: Button component ...prop 누락 추가
  components/core/Button/Button.tsx
  stories/Button.stories.tsx
Labels: Fix, FE_강혁준
