Repository OZ-Coding-School/oz_02_collabo-007, pull requests merged in 2024-06, with the labels that each got.

#113 refactor: myPage/competition 페이지 리팩토링
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/signin/LoadingContainer.tsx
  components/module/CompListOptionMenuButton/CompListOptionMenuButton.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/organism/SignInPage/SignInForm.tsx
  styles/globals.css
Labels: Refactor, FE_전소희

#115 refactor : 경기 날짜 formatDate 함수 추가
  components/module/CompInfoCard/CompInfoCard.tsx
Labels: Refactor, FE_이현경

#116 feat : Ranking UI 구현
  app/ranking/page.tsx
  components/module/RankingInfoCard/RankingInfoCard.tsx
Labels: Feat, FE_이현경

#120 feat : 로딩 스피너 추가
  app/(profile)/user/[id]/record/loading.tsx
  app/competition/loading.tsx
  app/mypage/loading.tsx
  app/signin/loading.tsx
Labels: FE_전소희, Feat, FE_이현경

#121 feat : Search Input 추가
  app/ranking/page.tsx
Labels: Feat, FE_이현경

#123 feat: 대회 신청 조회 페이지
  app/_actions/signUpUser.ts
  app/mypage/edit/page.tsx
  components/core/Button/Button.tsx
  components/module/CompDetailSection/CompDetailSection.tsx
  components/module/Modal/Modal.tsx
  components/module/ModalContent/ModalContent.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerList.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerModal.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/ClubField/ClubItem.tsx
  components/organism/SignUpPage/ClubField/ClubList.tsx
  components/organism/SignUpPage/ClubField/ClubModal.tsx
  components/organism/SignUpPage/SignUpForm.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  lib/hook/useClubList.ts
Labels: FE_강혁준, Feat

#126 feat : 이름 변경, 둘러보기 버튼 추가
  app/signin/page.tsx
  components/organism/CompetitionPage/DetailPage/CompButton/CompButton.tsx
  components/organism/SignInPage/SignInFormContent.tsx
Labels: Feat, FE_이현경

#130 refactor: 대회페이지 수정사항 적용
  @types/competition.d.ts
  app/_actions/getCompData.ts
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/page.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/module/Navbar/Navbar.tsx
  constants/competition/competition.ts
  lib/utils/truncateText.ts
Labels: Refactor, FE_전소희

#131 refactor: 미들웨어, 회원 수정 리팩토링
  app/competition/[id]/success/layout.tsx
  app/competition/[id]/success/page.tsx
  app/mypage/page.tsx
  components/core/Alert/Alert.tsx
  components/organism/MyPage/SignOutButton/SignOutButton.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
  middleware.ts
Labels: Refactor, FE_강혁준

#135 fix: 빌드에러 수정
  @types/competition.d.ts
  components/module/CompListOptionMenuButton/CompListOptionMenuButton.tsx
  components/organism/CompetitionPage/CompListFilter/CompListFilter.tsx
  constants/competition/competition.ts
Labels: Fix, FE_전소희

#133 feat : 이미지 배너 아이콘 추가
  components/module/CompInfoCard/CompInfoCard.tsx
  components/organism/CompetitionPage/DetailPage/ImageBanner/ImageBanner.tsx
  constants/competitionDetail.ts
Labels: Refactor, Feat, FE_이현경

#139 fix: compList 에러/버그 수정
  @types/competition.d.ts
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/page.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/organism/CompetitionPage/CompListFilter/CompListFilter.tsx
  constants/competition.ts
Labels: Fix, FE_전소희

#142 feat : 대회현황 페이지 구현
  @types/competition.d.ts
  app/_actions/getCompProgress.ts
  app/competition/[id]/progress/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/core/CompNavigation/TapGroup.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/MatchResultCard/MatchResultCard.tsx
  components/organism/CompetitionProgressPage/CompInfoCard.tsx
  components/organism/CompetitionProgressPage/MatchCard.tsx
  components/organism/CompetitionProgressPage/MatchList.tsx
  components/organism/CompetitionProgressPage/MatchScoreCard.tsx
  components/organism/CompetitionProgressPage/MatchUsersCard.tsx
Labels: Refactor, FE_전소희, Feat, FE_이현경

#143 refactor: 대회 신청, 대회 신청 조회 페이지 리팩토링
  @types/apply.d.ts
  @types/club.d.ts
  @types/user.d.ts
  app/_actions/cancelCompetition.ts
  app/_asset/icons/clock.svg
  app/api/competitions/[id]/application/cancel/route.ts
  app/competition/[id]/success/page.tsx
  app/mypage/competition/page.tsx
  components/core/HeaderBar/HeaderBar.tsx
  components/module/Navbar/Navbar.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/ApplyFormContent.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerItem.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerList.tsx
  components/organism/CompetitionPage/SuccessPage/ApplyPolicy/ApplyPolicy.tsx
  components/organism/CompetitionPage/SuccessPage/FeeCard/FeeCard.tsx
  components/organism/CompetitionPage/SuccessPage/ParticipantInfo/ParticipantInfo.tsx
  components/organism/CompetitionPage/SuccessPage/SuccessButtons/SuccessButtons.tsx
  components/organism/MyPage/MyProfileCard/ClubTab/ClubTab.tsx
  lib/hook/useApplyForm.ts
Labels: Refactor, FE_강혁준

#144 feat: 액세스 토큰 재발행 기능 추가
  app/_actions/getCompDetail.ts
  app/_actions/renewAccessToken.ts
  lib/utils/fetchWithToken.ts
  middleware.ts
Labels: FE_강혁준, Feat

#147 refactor: CompNavigation 수정
  app/_actions/getCompProgress.ts
  app/competition/[id]/progress/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/core/CompNavigation/TapGroup.tsx
  components/organism/CompetitionProgressPage/MatchScoreCard.tsx
  stories/MatchResultCard.stories.tsx
Labels: Refactor, FE_전소희, FE_이현경

#145 feat : 내가 참가 신청한 대회 api 연동
  components/core/CompNavigation/Tab.tsx
  components/module/MatchResultCard/MatchResultCard.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSection.tsx
Labels: Refactor, FE_전소희, Feat, FE_이현경

#149 feat: 액세스 토큰 재발행 기능 추가 #140
  app/_actions/cancelCompetition.ts
  app/_actions/getApplyResult.ts
  app/_actions/getMyData.ts
  app/_actions/getPartner.ts
  app/_actions/renewAccessToken.ts
  app/_actions/verifyToken.ts
  app/mypage/competition/page.tsx
  components/module/CancelAlert/CancelAlert.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerItem.tsx
  components/organism/CompetitionPage/SuccessPage/SuccessButtons/SuccessButtons.tsx
  lib/hook/useClubList.ts
  lib/utils/hangulToJamo.ts
  middleware.ts
Labels: FE_강혁준, Feat

#148 refactor : competition페이지 Navtab 변경
  @types/competition.d.ts
  app/_actions/getCompData.ts
  app/_actions/getMyCompData.ts
  app/competition/[id]/progress/page.tsx
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/mypage/page.tsx
  app/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/core/CompNavigation/TapGroup.tsx
  components/core/NavItem/NavItem.tsx
  components/core/Skeleton/CompListSkeleton.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompListSection/CompList/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/module/MyCompMatchCard/MyCompMatchCard.tsx
  components/module/Navbar/Navbar.tsx
  constants/competition.ts
Labels: Refactor, FE_전소희, FE_이현경

#152 feat: 대회 현황 페이지 구현
  @types/competition.d.ts
  app/_actions/getCompData.ts
  app/_actions/getCompProgress.ts
  app/competition/[id]/progress/page.tsx
  app/page.tsx
  components/module/CompInfoCard/CompInfoCard.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/CompetitionPage/DetailPage/CompButton/CompButton.tsx
  components/organism/CompetitionProgressPage/MatchCard.tsx
  components/organism/CompetitionProgressPage/MatchList.tsx
  components/organism/CompetitionProgressPage/MatchScoreCard.tsx
  components/organism/CompetitionProgressPage/MatchUsersCard.tsx
  constants/competition.ts
Labels: FE_전소희, Feat, FE_이현경

#154 refactor: 홈, 대회, 내가 신청한 페이지 리팩토링
  @types/competition.d.ts
  app/_actions/changePassword.ts
  app/_actions/getApplyResult.ts
  app/_actions/getCompData.ts
  app/_actions/getMyCompData.ts
  app/_actions/getMyData.ts
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/page.tsx
  app/signin/page.tsx
  components/core/Avatar/ProfileAvatar.tsx
  components/core/Skeleton/CompListSkeleton.tsx
  components/module/CompCard/CompCard.tsx
  components/module/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompListSection/CompList/CompCard/CompCard.tsx
  components/module/CompListSection/CompList/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompListSection/CompList/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompListSection/CompList/CompList.tsx
  components/module/CompListSection/CompListSection.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompInfo/CompInfo.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompListFilter/CompListFilter.tsx
  components/organism/CompetitionProgressPage/MatchList.tsx
  components/organism/HomPage/HomeCompInfo/HomeCompInfo.tsx
  components/organism/HomPage/HomeMyCompInfo/HomeMyCompInfo.tsx
  components/organism/HomPage/HomeMyCompInfoCard/HomeMyCompInfoCard.tsx
  components/organism/MyPage/MyCompInfo/MyCompInfo.tsx
  components/organism/MyPage/SignOutButton/SignOutButton.tsx
  constants/competition.ts
  lib/utils/fetchWithToken.ts
  lib/utils/filterCompetition.ts
  middleware.ts
Labels: Refactor, FE_강혁준, FE_전소희, FE_이현경

#156 refactor : 코드 리팩토링 , 미사용 상수 제거, 스켈레톤 작업
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  app/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/core/Skeleton/CompListSkeleton.tsx
  components/module/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/Navbar/Navbar.tsx
  components/organism/HomPage/HomeCompInfo/HomeCompInfo.tsx
  constants/competition.ts
Labels: Refactor, FE_전소희, Feat, FE_이현경

#158 refactor: 대회 페이지 리팩토링
  app/page.tsx
  components/organism/CompetitionProgressPage/MatchCard.tsx
  components/organism/CompetitionProgressPage/MatchList.tsx
  styles/globals.css
Labels: FE_강혁준, Feat

#164 refactor : 코드 리팩토링 , 미사용 상수 제거, 스켈레톤 작업
  @types/competition.d.ts
  components/module/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompCard/NextMatchInfo/NextMatchInfo.tsx
  tailwind.config.ts
Labels: Refactor, FE_전소희, Feat

#165 refactor: 대회 현황 페이지
  app/competition/[id]/progress/page.tsx
  components/core/Skeleton/MatchListSkeleton.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
Labels: Refactor, FE_전소희, Feat

#166 refactor: 페이지별 레이아웃
  app/competition/page.tsx
  app/mypage/competition/page.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompInfo/CompInfo.tsx
  components/organism/HomPage/HomeCompInfo/HomeCompInfo.tsx
  components/organism/MyPage/MyCompInfo/MyCompInfo.tsx
Labels: Fix, Refactor, FE_전소희

#167 refator: 모바일 환경에서의 에러 수정
  app/_actions/applyCompetition.ts
  app/mypage/competition/page.tsx
  app/mypage/edit/page.tsx
  app/signup/layout.tsx
  components/module/ModalContent/ModalContent.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/ApplyFormContent.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerModal.tsx
  components/organism/CompetitionPage/SuccessPage/SuccessButtons/SuccessButtons.tsx
  components/organism/SignUpPage/ClubField/ClubList.tsx
  components/organism/SignUpPage/SignUpFormContent.tsx
Labels: Refactor, FE_강혁준

#168 feat: 대회 결과 페이지
  @types/competition.d.ts
  app/_actions/getCompResult.ts
  app/competition/[id]/result/page.tsx
  app/mypage/edit/page.tsx
  app/signup/layout.tsx
  components/module/CompDetailSection/CompDetailSection.tsx
  components/module/ResultCard/ResultCard.tsx
  components/organism/CompetitionPage/DetailPage/ImageBanner/ImageBanner.tsx
Labels: FE_강혁준, Feat

#171 refactor: 대회 티어 필터 리팩토링
  @types/tier.d.ts
  app/_actions/getCompData.ts
  app/_actions/getTiers.ts
  app/competition/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/module/Navbar/Navbar.tsx
  components/organism/CompetitionPage/CompetitionHomePage/TierFilter/TierFilter.tsx
  lib/utils/filterCompetition.ts
Labels: Refactor, FE_강혁준, FE_전소희

#173 refactor: css(폰트 및 selecte 태그) 수정
  components/core/CompNavigation/Tab.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompListFilter/CompListFilter.tsx
  components/organism/CompetitionPage/CompetitionHomePage/TierFilter/TierFilter.tsx
Labels: Refactor, FE_강혁준

#172 refactor: 내 전적 페이지 수정
  @types/record.d.ts
  app/(profile)/user/[id]/record/page.tsx
  app/_actions/getMyRecord.ts
  components/core/Input/Input.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/HomPage/HomeCompInfo/HomeCompInfo.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSection.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSectionHeader/RecordSectionHeader.tsx
  components/organism/SignUpPage/ChangePasswordForm/ChangePasswordField/ChangePasswordField.tsx
  components/organism/SignUpPage/ConfirmPasswordField/ConfirmPasswordField.tsx
  components/organism/SignUpPage/PasswordField/PasswordField.tsx
  components/organism/SignUpPage/PhoneField/PhoneField.tsx
Labels: Refactor, FE_강혁준, FE_전소희

#175 feat: 랭킹 페이지 구현
  @types/ranking.d.ts
  app/_actions/getCompData.ts
  app/_actions/getMyRanking.ts
  app/_actions/getTiers.ts
  app/_actions/getUserRanking.ts
  app/ranking/page.tsx
  components/core/CompNavigation/Tab.tsx
  components/core/CompNavigation/TapGroup.tsx
  components/module/RankingInfoCard/RankingInfoCard.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompListFilter/CompListFilter.tsx
  components/organism/CompetitionPage/CompetitionHomePage/TierFilter/TierFilter.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSection.tsx
  components/organism/RankingPage/MyRankingCard.tsx
  components/organism/RankingPage/RankingBoard/RankingBoard.tsx
  components/organism/RankingPage/RankingBoardHeader/RankingBoardHeader.tsx
  components/organism/RankingPage/RankingFilters/RankingFilters.tsx
  components/organism/RankingPage/RankingHeader/RankingHeader.tsx
  components/organism/RankingPage/TotalRankingHeader/TotalRankingHeader.tsx
  constants/competition.ts
Labels: FE_강혁준, FE_전소희, Feat

#176 feat: 랭킹 페이지 구현
  app/_actions/applyCompetition.ts
  app/_actions/cancelCompetition.ts
  app/_actions/changePassword.ts
  app/_actions/editUser.ts
  app/_actions/getApplyResult.ts
  app/_actions/getCompData.ts
  app/_actions/getCompDetail.ts
  app/_actions/getCompProgress.ts
  app/_actions/getMyCompData.ts
  app/_actions/getMyRanking.ts
  app/_actions/getPartner.ts
  app/_actions/getUserRanking.ts
  app/page.tsx
  app/ranking/page.tsx
  components/module/Navbar/Navbar.tsx
  components/module/RankingInfoCard/RankingInfoCard.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompListFilter/CompListFilter.tsx
  components/organism/CompetitionPage/CompetitionHomePage/TierFilter/TierFilter.tsx
  components/organism/RankingPage/MyRankingCard.tsx
  components/organism/RankingPage/RankingBoard/RankingBoard.tsx
  components/organism/RankingPage/RankingBoardHeader/RankingBoardHeader.tsx
  components/organism/RankingPage/RankingFilters/RankingFilters.tsx
  components/organism/RankingPage/RankingHeader/RankingHeader.tsx
  components/organism/RankingPage/RankingSection/RankingSection.tsx
  components/organism/RankingPage/TotalRankingHeader/TotalRankingHeader.tsx
  components/organism/RankingPage/YearFilter/YearFilter.tsx
  lib/hook/useQueryString.ts
  middleware.ts
  tailwind.config.ts
Labels: FE_강혁준, FE_전소희, Feat

#177 feat: 클럽 랭킹 페이지
  @types/ranking.d.ts
  app/_actions/getMyRanking.ts
  app/_actions/getUserRanking.ts
  app/ranking/error.tsx
  components/module/RankingInfoCard/RankingInfoCard.tsx
  components/organism/CompetitionPage/SuccessPage/SuccessButtons/SuccessButtons.tsx
  components/organism/RankingPage/MyRankingCard.tsx
  components/organism/RankingPage/RankingBoard/RankingBoard.tsx
  components/organism/RankingPage/RankingFilters/RankingFilters.tsx
  components/organism/RankingPage/RankingSection/RankingSection.tsx
  lib/hook/useQueryString.ts
Labels: FE_강혁준, FE_전소희, Feat

#179 feat: 대표 랭킹 설정 페이지 구현
  @types/ranking.d.ts
  app/_actions/getMyprofileRanking.ts
  app/_asset/icons/check.svg
  app/mypage/ranking/page.tsx
  components/organism/MyPage/RankingButtomList/RankingButtonList.tsx
  components/organism/MyPage/RankingButton/RankingButton.tsx
Labels: FE_강혁준, FE_전소희, Feat

#180 feat: 대표 랭킹 설정 페이지 구현
  @types/user.d.ts
  app/_actions/changeTitleRanking.ts
  app/_actions/getMyTitleRanking.ts
  app/api/ranking/route.ts
  app/mypage/page.tsx
  app/mypage/ranking/[gender]/page.tsx
  app/mypage/ranking/page.tsx
  app/page.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/MyPage/MyProfileCard/MyProfileCard.tsx
  components/organism/MyPage/MyProfileCard/ProfileTab/ProfileTab.tsx
  components/organism/MyPage/RankingButton/RankingButton.tsx
  components/organism/MyPage/RankingButtonList/RankingButtonList.tsx
  lib/utils/hangulToJamo.ts
Labels: FE_강혁준, FE_전소희, Feat

#181 fix: 클럽 중복 신청 에러 수정
  components/organism/SignUpPage/ClubField/ClubField.tsx
Labels: Fix, FE_강혁준

#183 feat: 프로필 페이지 구현
  @types/user.d.ts
  app/(profile)/club/[id]/member/page.tsx
  app/(profile)/club/[id]/page.tsx
  app/(profile)/loading.tsx
  app/(profile)/team/[id]/member/page.tsx
  app/(profile)/team/[id]/page.tsx
  app/(profile)/user/[id]/page.tsx
  app/_actions/applyCompetition.ts
  app/_actions/cancelCompetition.ts
  app/_actions/getClubData.ts
  app/_actions/getClubMember.ts
  app/_actions/getCompData.ts
  app/_actions/getTeamData.ts
  app/_actions/getTeamMember.ts
  app/_actions/getUserData.ts
  app/competition/page.tsx
  components/module/CompInfoCard/CompInfoCard.tsx
  components/module/MemberProfile/MemberProfile.tsx
  components/module/MemberSection/MemberSection.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/module/UserProfile/UserInfoCard/UserInfoCard.tsx
  components/module/UserProfile/UserProfile.tsx
  components/organism/CompetitionPage/CompetitionHomePage/CompListFilter/CompListFilter.tsx
  components/organism/CompetitionPage/CompetitionHomePage/TierFilter/TierFilter.tsx
  components/organism/CompetitionPage/SuccessPage/SuccessButtons/SuccessButtons.tsx
  components/organism/CompetitionProgressPage/CompInfoCard.tsx
  components/organism/CompetitionProgressPage/MatchCard.tsx
  components/organism/MyPage/MyProfileCard/ProfileTab/ProfileTab.tsx
  components/organism/MyPage/RecentRecordSection/RecentRecordSection.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSectionHeader/RecordSectionHeader.tsx
  components/organism/RankingPage/RankingBoardHeader/RankingBoardHeader.tsx
  components/organism/RankingPage/RankingFilters/RankingFilters.tsx
  components/organism/RankingPage/YearFilter/YearFilter.tsx
  constants/competitionDetail.ts
  tailwind.config.ts
Labels: FE_강혁준, FE_전소희, Feat, FE_이현경

#188 feat: 유저 프로필 랭킹 추가
  app/(profile)/user/[id]/page.tsx
  app/_actions/getUserListRanking.ts
  app/_actions/getUserRanking.ts
  app/mypage/page.tsx
  app/mypage/ranking/[gender]/page.tsx
  app/mypage/ranking/[id]/page.tsx
  components/module/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/organism/MyPage/RankingButtonList/RankingButtonList.tsx
  components/organism/ProfilePage/UserPage/UserProfileRankingCard/UserProfileRankingCard.tsx
  components/organism/RankingPage/RankingSection/RankingSection.tsx
Labels: FE_전소희, Feat, FE_이현경

#191 refactor: 모달 input 자동 포커스
  app/_actions/getUserRanking.ts
  app/signup/layout.tsx
  components/core/HeaderBar/HeaderBar.tsx
  components/module/Modal/Modal.tsx
  components/module/ModalContent/ModalContent.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerField.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyForm/PartnerField/PartnerModal.tsx
  components/organism/SignUpPage/ClubField/ClubField.tsx
  components/organism/SignUpPage/ClubField/ClubModal.tsx
Labels: Refactor, FE_강혁준

#189 feat: TODO Skeleton 구현
  app/(profile)/user/[id]/page.tsx
  app/ranking/page.tsx
  components/core/Skeleton/MyRankingCardSkeleton.tsx
  components/core/Skeleton/RankingBoardSkeleton.tsx
  components/core/Skeleton/RecentRecordSectionSkeleton.tsx
  components/core/Skeleton/UserProfileSkeleton.tsx
Labels: Feat, FE_이현경

#190 feat: 유저 프로필 랭킹 추가, competition 타입 리팩토링, 팀 랭킹 데이터 추가
  @types/apply.d.ts
  @types/competition.d.ts
  @types/ranking.d.ts
  @types/record.d.ts
  @types/team.d.ts
  @types/user.d.ts
  app/(profile)/team/[id]/page.tsx
  app/competition/[id]/apply/page.tsx
  app/competition/[id]/progress/page.tsx
  app/competition/[id]/result/page.tsx
  app/mypage/ranking/[id]/page.tsx
  components/module/CompCard/CompCard.tsx
  components/module/CompCard/CompCardMatchDetail/CompCardMatchDetail.tsx
  components/module/CompCard/CompStatusButton/CompStatusButton.tsx
  components/module/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/CompCard/NextMatchInfo/NextMatchInfo.tsx
  components/module/CompDetailSection/CompDetailSection.tsx
  components/module/CompInfoCard/CompInfoCard.tsx
  components/module/MemberProfile/MemberProfile.tsx
  components/module/MemberSection/MemberSection.tsx
  components/module/UserProfile/UserHighlightRankingCard/UserHighlightRankingCard.tsx
  components/organism/CompetitionPage/ApplyPage/ApplyPageSection.tsx
  components/organism/CompetitionPage/DetailPage/CompDetail/CompDetail.tsx
  components/organism/CompetitionProgressPage/CompInfoCard.tsx
  components/organism/HomPage/HomeMyCompInfo/HomeMyCompInfo.tsx
  components/organism/HomPage/HomeMyCompInfoCard/HomeMyCompInfoCard.tsx
  components/organism/MyPage/MyCompInfo/MyCompInfo.tsx
  components/organism/MyPage/MyProfileCard/ProfileTab/ProfileTab.tsx
  components/organism/MyPage/RankingButton/RankingButton.tsx
  components/organism/MyPage/RankingButtonList/RankingButtonList.tsx
  components/organism/ProfilePage/ClubPage/InfoSection/InfoSection.tsx
  components/organism/ProfilePage/UserPage/RecordSection/RecordSectionHeader/RecordSectionHeader.tsx
  components/organism/ProfilePage/UserPage/UserProfileRankingCard/UserProfileRankingCard.tsx
  constants/competition.ts
  lib/utils/filterCompetition.ts
  lib/utils/printMatchTypeInfo.ts
Labels: Fix, Refactor, FE_전소희

#194 fix: 버그, 에러 수정
  app/(profile)/club/[id]/page.tsx
  components/core/Avatar/Avatar.tsx
  components/core/Avatar/ProfileAvatar.tsx
  components/core/CompNavigation/TapGroup.tsx
  components/module/CompCard/CompCard.tsx
  components/module/CompCard/CompStatusInfo/CompStatusInfo.tsx
  components/module/MemberProfile/MemberProfile.tsx
  components/module/RankingInfoCard/RankingInfoCard.tsx
  components/module/ResultCard/ResultCard.tsx
  components/organism/CompetitionPage/DetailPage/CompDetail/CompDetail.tsx
  components/organism/CompetitionPage/DetailPage/ImageBanner/ImageBanner.tsx
  components/organism/CompetitionPage/SuccessPage/ParticipantInfo/ParticipantInfo.tsx
  components/organism/CompetitionProgressPage/MatchList.tsx
  components/organism/MyPage/MyProfileCard/ProfileTab/ProfileTab.tsx
  components/organism/ProfilePage/ClubPage/InfoSection/InfoSection.tsx
  components/organism/RankingPage/RankingBoard/RankingBoard.tsx
  components/organism/SignUpPage/ClubField/ClubItem.tsx
  components/organism/SignUpPage/ProfileField/ProfileField.tsx
  lib/utils/filterCompetition.ts
Labels: Fix, FE_전소희, FE_이현경
